"""Report generation service — automated intelligence briefs in PDF / HTML.

Generates monthly or on-demand reports per region using:
1. Jinja2 templates → HTML rendering
2. WeasyPrint → PDF conversion
3. MinIO / S3 → persistent storage

Each report contains:
- CESI trend chart (score + severity over time)
- Per-layer anomaly breakdown
- Crisis probability forecasts
- Triggered alerts during the period
- Spatial contagion summary
"""

from __future__ import annotations

import io
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import structlog
from sqlalchemy import and_, select, func
from sqlalchemy.ext.asyncio import AsyncSession

from frr.config import get_settings
from frr.db.models import (
    AlertHistory,
    CESIScore,
    CrisisType,
    Prediction,
    Region,
    ReportFormat,
    ReportJob,
    SignalLayer,
)

logger = structlog.get_logger(__name__)

# ── HTML Template ──────────────────────────────────────────────────────

_REPORT_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>FRR Intelligence Brief — {{ region_name }}</title>
<style>
  body { font-family: 'Segoe UI', Arial, sans-serif; margin: 2rem; color: #1a1a1a; }
  h1 { color: #0f172a; border-bottom: 3px solid #3b82f6; padding-bottom: 0.5rem; }
  h2 { color: #1e40af; margin-top: 2rem; }
  .meta { color: #64748b; font-size: 0.9rem; margin-bottom: 2rem; }
  table { border-collapse: collapse; width: 100%; margin: 1rem 0; }
  th, td { border: 1px solid #e2e8f0; padding: 0.5rem 0.75rem; text-align: left; }
  th { background: #f1f5f9; font-weight: 600; }
  .badge { padding: 2px 8px; border-radius: 4px; font-size: 0.8rem; color: white; }
  .badge-stable { background: #22c55e; }
  .badge-elevated { background: #eab308; color: #1a1a1a; }
  .badge-concerning { background: #f97316; }
  .badge-high_risk { background: #ef4444; }
  .badge-critical { background: #7f1d1d; }
  .summary-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; margin: 1rem 0; }
  .summary-card { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 1rem; }
  .score-big { font-size: 2.5rem; font-weight: 700; color: #0f172a; }
  footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #e2e8f0; color: #94a3b8; font-size: 0.8rem; }
</style>
</head>
<body>

<h1>🌐 Future Risk Radar — Intelligence Brief</h1>
<div class="meta">
  <strong>Region:</strong> {{ region_name }} ({{ region_code }})<br>
  <strong>Period:</strong> {{ period_start }} — {{ period_end }}<br>
  <strong>Generated:</strong> {{ generated_at }}
</div>

<div class="summary-grid">
  <div class="summary-card">
    <div>Latest CESI Score</div>
    <div class="score-big">{{ "%.1f"|format(latest_score) }}</div>
    <span class="badge badge-{{ severity }}">{{ severity | upper }}</span>
  </div>
  <div class="summary-card">
    <div>Alerts Fired</div>
    <div class="score-big">{{ alerts_count }}</div>
    <span>during this period</span>
  </div>
</div>

<h2>CESI Score History</h2>
<table>
  <tr><th>Date</th><th>Score</th><th>Severity</th></tr>
  {% for point in cesi_history %}
  <tr>
    <td>{{ point.scored_at }}</td>
    <td>{{ "%.2f"|format(point.score) }}</td>
    <td><span class="badge badge-{{ point.severity }}">{{ point.severity }}</span></td>
  </tr>
  {% endfor %}
</table>

<h2>Layer Breakdown (Latest)</h2>
<table>
  <tr><th>Layer</th><th>Raw Anomaly</th><th>Weight</th><th>Contribution</th></tr>
  {% for layer, data in layer_scores.items() %}
  <tr>
    <td>{{ layer }}</td>
    <td>{{ "%.2f"|format(data.get('raw_anomaly', 0)) }}</td>
    <td>{{ "%.2f"|format(data.get('weight', 0)) }}</td>
    <td>{{ "%.2f"|format(data.get('contribution', 0)) }}</td>
  </tr>
  {% endfor %}
</table>

<h2>Crisis Probability Forecasts</h2>
<table>
  <tr><th>Crisis Type</th><th>Probability</th><th>CI Lower</th><th>CI Upper</th></tr>
  {% for crisis, data in crisis_probabilities.items() %}
  <tr>
    <td>{{ crisis }}</td>
    <td>{{ "%.1f%%"|format(data.get('probability', 0) * 100) }}</td>
    <td>{{ "%.1f%%"|format(data.get('ci_lower', 0) * 100) }}</td>
    <td>{{ "%.1f%%"|format(data.get('ci_upper', 0) * 100) }}</td>
  </tr>
  {% endfor %}
</table>

{% if alerts %}
<h2>Triggered Alerts</h2>
<table>
  <tr><th>Fired At</th><th>Message</th><th>Metric Value</th><th>Delivered</th></tr>
  {% for alert in alerts %}
  <tr>
    <td>{{ alert.fired_at }}</td>
    <td>{{ alert.message }}</td>
    <td>{{ "%.2f"|format(alert.metric_value) }}</td>
    <td>{{ "✓" if alert.delivered else "✗" }}</td>
  </tr>
  {% endfor %}
</table>
{% endif %}

<footer>
  Generated by Future Risk Radar v{{ version }} | Confidential<br>
  &copy; {{ year }} Future Risk Radar
</footer>

</body>
</html>
"""


# ── Data collection ────────────────────────────────────────────────────

async def _collect_report_data(
    session: AsyncSession,
    region_code: str | None,
    period_start: datetime,
    period_end: datetime,
) -> dict[str, Any]:
    """Collect all data needed for the report template."""
    data: dict[str, Any] = {
        "region_code": region_code or "GLOBAL",
        "region_name": "Global Overview",
        "period_start": period_start.strftime("%Y-%m-%d"),
        "period_end": period_end.strftime("%Y-%m-%d"),
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        "version": get_settings().api_version,
        "year": datetime.now(timezone.utc).year,
    }

    region = None
    if region_code:
        result = await session.execute(select(Region).where(Region.code == region_code))
        region = result.scalar_one_or_none()
        if region:
            data["region_name"] = region.name

    # CESI history
    cesi_query = (
        select(CESIScore)
        .where(and_(CESIScore.scored_at >= period_start, CESIScore.scored_at <= period_end))
        .order_by(CESIScore.scored_at.desc())
    )
    if region:
        cesi_query = cesi_query.where(CESIScore.region_id == region.id)
    cesi_result = await session.execute(cesi_query.limit(100))
    cesi_rows = cesi_result.scalars().all()

    data["cesi_history"] = [
        {
            "score": c.score,
            "severity": c.severity.value if hasattr(c.severity, "value") else str(c.severity),
            "scored_at": c.scored_at.strftime("%Y-%m-%d %H:%M"),
        }
        for c in cesi_rows
    ]

    # Latest score
    if cesi_rows:
        latest = cesi_rows[0]
        data["latest_score"] = latest.score
        data["severity"] = latest.severity.value if hasattr(latest.severity, "value") else str(latest.severity)
        data["layer_scores"] = latest.layer_scores or {}
        data["crisis_probabilities"] = latest.crisis_probabilities or {}
    else:
        data["latest_score"] = 0.0
        data["severity"] = "stable"
        data["layer_scores"] = {}
        data["crisis_probabilities"] = {}

    # Alerts during period
    alerts_query = (
        select(AlertHistory)
        .where(and_(AlertHistory.fired_at >= period_start, AlertHistory.fired_at <= period_end))
        .order_by(AlertHistory.fired_at.desc())
    )
    if region_code:
        alerts_query = alerts_query.where(AlertHistory.region_code == region_code)
    alerts_result = await session.execute(alerts_query.limit(50))
    alert_rows = alerts_result.scalars().all()

    data["alerts"] = [
        {
            "fired_at": a.fired_at.strftime("%Y-%m-%d %H:%M"),
            "message": a.message[:200],
            "metric_value": a.metric_value,
            "delivered": a.delivered,
        }
        for a in alert_rows
    ]
    data["alerts_count"] = len(alert_rows)

    return data


# ── Rendering ──────────────────────────────────────────────────────────

def _render_html(data: dict[str, Any]) -> str:
    """Render the HTML report from template + data."""
    from jinja2 import Template

    template = Template(_REPORT_HTML_TEMPLATE)
    return template.render(**data)


def _html_to_pdf(html: str) -> bytes:
    """Convert HTML string to PDF bytes using WeasyPrint."""
    try:
        from weasyprint import HTML
        pdf_bytes = HTML(string=html).write_pdf()
        return pdf_bytes
    except ImportError:
        logger.warning("WeasyPrint not installed — returning HTML as fallback")
        return html.encode("utf-8")


# ── S3/MinIO upload ───────────────────────────────────────────────────

async def _upload_to_s3(key: str, data: bytes, content_type: str) -> str:
    """Upload report file to MinIO/S3 bucket, return the object key."""
    import boto3
    from botocore.config import Config as BotoConfig

    settings = get_settings()
    s3 = boto3.client(
        "s3",
        endpoint_url=settings.s3_endpoint,
        aws_access_key_id=settings.s3_access_key,
        aws_secret_access_key=settings.s3_secret_key.get_secret_value(),
        config=BotoConfig(signature_version="s3v4"),
    )

    bucket = settings.reports_s3_bucket
    # Ensure bucket exists
    try:
        s3.head_bucket(Bucket=bucket)
    except Exception:
        s3.create_bucket(Bucket=bucket)

    s3.put_object(Bucket=bucket, Key=key, Body=data, ContentType=content_type)
    logger.info("Report uploaded to S3", bucket=bucket, key=key, size=len(data))
    return key


# ── Main entry point ──────────────────────────────────────────────────

async def generate_report(
    session: AsyncSession,
    job: ReportJob,
) -> ReportJob:
    """Generate a full intelligence report for the given job parameters.

    Updates the ``ReportJob`` row with status, file path, and completion time.
    """
    try:
        job.status = "generating"
        await session.commit()

        # Collect data
        data = await _collect_report_data(
            session,
            region_code=job.region_code,
            period_start=job.period_start,
            period_end=job.period_end,
        )

        # Render HTML
        html = _render_html(data)

        # Convert to PDF if needed
        report_format = job.report_format
        if hasattr(report_format, "value"):
            report_format = report_format.value

        region_slug = (job.region_code or "global").lower()
        ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")

        if report_format == "pdf":
            content = _html_to_pdf(html)
            ext = "pdf"
            content_type = "application/pdf"
        else:
            content = html.encode("utf-8")
            ext = "html"
            content_type = "text/html"

        # Upload to S3
        s3_key = f"reports/{region_slug}/{ts}_brief.{ext}"
        await _upload_to_s3(s3_key, content, content_type)

        # Update job
        job.file_path = s3_key
        job.file_size_bytes = len(content)
        job.status = "completed"
        job.completed_at = datetime.now(timezone.utc)

    except Exception as e:
        logger.error("Report generation failed", error=str(e), job_id=str(job.id))
        job.status = "failed"
        job.error = str(e)[:1000]

    await session.commit()
    return job
